### ISSUE TITLE
Tablero del jugador 

### ISSUE THREAD

**Issue by Bfglix** [Hellogark/TuaregWeb#2]
El usuario debe poder visualizar su tablero y la carta que lleva en su mano.

- [x] Creación del tablero del jugador (Vista)

- [x] Asociar cada tablero con el jugador 1 o jugador 2 (Modelo y Vista)

- [x] Actualizar contenidos de los tableros del jugador en el transcurso de una partida (Modelo)

- [x] Actualizar espacio de "carta en mano" con la carta en mano actual en el transcurso de la partida. (Modelo y Vista)

**Comment by Hellogark** [comment]
Se cerró el issue con el commit #35

**Comment by Bfglix** [comment]
Hecho hace un dia
