### ISSUE TITLE
Al usar la ampliación de tribu y querer comprar no se resta su coste al jugador

### ISSUE THREAD

**Issue by Kusanaky** [Hellogark/TuaregWeb#36]
La compra por medio de la carta de borde ampliación de tribu tiene problemas al no restar su coste al comprar.

**Comment by Bfglix** [comment]
Se necesitan mas detalles , tipo de carta que se usó , costo de la carta y una foto del log de la pagina

**Comment by Kusanaky** [comment]
La carta que se compró por medio de aplicación de tribu fue la del id 17 camello, costo 1 dátil, 2 pimientas, 2 sales, no se tiene foto

**Comment by Bfglix** [comment]
Se ha probado la carta , funciona , probablemente estabas comprándola , cuando se apagó o reinició el servidor.
![todobien2](https://user-images.githubusercontent.com/25822786/33301422-f935ce60-d3b2-11e7-991b-9e3580c10f0c.PNG)
