### ISSUE TITLE
No aparece el popup al comprar cartas de tribu

### ISSUE THREAD

**Issue by Kusanaky** [Hellogark/TuaregWeb#37]
Al querer comprar una carta de tribu el popup para las opciones no aparece y el juego se queda congelado por la falta de continuación el proceso.
La concurrencia del fallo no se conoce.

**Comment by Bfglix** [comment]
Se necesitan mas detalles , tipo de carta que se usó , costo de la carta y una foto del log de la pagina

**Comment by Kusanaky** [comment]
![image](https://user-images.githubusercontent.com/25800489/33300993-93f03e3e-d3b0-11e7-84fe-d59e87000651.png)
No se tiene el log de la página

**Comment by Bfglix** [comment]
Es necesaria la foto del log, se ha probado esa carta y el error no se presenta.
![sinproblemas](https://user-images.githubusercontent.com/25822786/33301182-953fb53e-d3b1-11e7-886e-9b6670dec82f.PNG)
